export const FETCH_POKEMON_LIST = "FETCH_POKEMON_LIST";
export const FETCH_POKEMON_DETAIL = "FETCH_POKEMON_DETAIL";
export const STORE_POKEMON_DATA = "STORE_POKEMON_DATA";
export const UPDATE_POKEMON_DATA = "UPDATE_POKEMON_DATA";
export const DELETE_POKEMON_DATA = "DELETE_POKEMON_DATA";

export const FETCH_POKEMON_CATEGORY = "FETCH_POKEMON_CATEGORY";
export const FETCH_POKEMON_TYPE = "FETCH_POKEMON_TYPE";

export const FETCH_USER_DATA = "FETCH_USER_DATA";
export const STORE_USER_DATA = "STORE_USER_DATA";
